import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from "../components/NavBar";
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ISOaccess',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar />
      
      <main className='w-screen h-screen bg-base'>
        {children}
      </main>
      {/* <footer className='w-screen h-16 bg-base bottom-1'>
        <div className='flex justify-center items-center h-full'>
          <p className='text-gray-400 text-sm'>© {new Date().getFullYear()} ISOaccess</p>
        </div>
      </footer> */}

      <Script strategy="lazyOnload" id="clarity-script">
        {`
          (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
          })(window, document, "clarity", "script", "k3jei3fgfr");
        `}
      </Script>

      

      </body>
    </html>
  )
}
